@echo off

set JKSSOURCE=jks
set JKSDEST1=..\..\webservice
set JKSDEST2=..\..\semmi
set JKSDEST3=..\..\semmi
set SITEPATH=\src\main\dist\bin\jks

IF EXIST %JKSDEST1% (
	IF EXIST %JKSDEST1%%SITEPATH% RMDIR /S /Q %JKSDEST1%%SITEPATH%
	IF NOT EXIST %JKSDEST1%%SITEPATH% MD %JKSDEST1%%SITEPATH%
	xcopy %JKSSOURCE% %JKSDEST1%%SITEPATH% /S /E /H
	colorecho "jks copied to %JKSDEST1%%SITEPATH%" 14
)

IF EXIST %JKSDEST2% (
	IF EXIST %JKSDEST2%%SITEPATH% RMDIR /S /Q %JKSDEST2%%SITEPATH%
	IF NOT EXIST %JKSDEST2%%SITEPATH% MD %JKSDEST2%%SITEPATH%
	xcopy %JKSSOURCE% %JKSDEST2%%SITEPATH% /S /E /H
	colorecho "jks copied to %JKSDEST2%%SITEPATH%" 14
)

IF EXIST %JKSDEST3% (
	IF EXIST %JKSDEST3%%SITEPATH% RMDIR /S /Q %JKSDEST3%%SITEPATH%
	IF NOT EXIST %JKSDEST3%%SITEPATH% MD %JKSDEST3%%SITEPATH%
	xcopy %JKSSOURCE% %JKSDEST3%%SITEPATH% /S /E /H
	colorecho "jks copied to %JKSDEST3%%SITEPATH%" 14
)


set TLSSOURCE=tls
set TLSDEST1=..\..\keycloak\docker\cert

IF EXIST %TLSDEST1% (
	IF EXIST %TLSDEST1% RMDIR /S /Q %TLSDEST1%
	IF NOT EXIST %TLSDEST1% MD %TLSDEST1%
	xcopy %TLSSOURCE% %TLSDEST1% /S /E /H
	colorecho "tls copied to %TLSDEST1%" 14
)
