#docker compose for local development

version: '3.6'

networks:
    back-tier-net:
        driver: bridge
    monitoring:
        driver: bridge


services: 

    #####################################################################################                 
    sqlserver:
    #####################################################################################                 
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Passw0rd
        ports:
            - "1433:1433"
        volumes:
            - wsstepbystep_sqlserver:/var/opt/mssql
        networks: 
            back-tier-net:
                aliases:
                    - sqlserver.wsstepbystep.perit.hu
        hostname: sqlserver.wsstepbystep.perit.hu
            
  
    #####################################################################################                 
    keycloak:
    #####################################################################################                 
        container_name: "keycloak"
        #image: "jboss/keycloak:10.0.1"
        image: wsstepbystep_keycloak
        environment:
          - KEYCLOAK_USER=admin
          - KEYCLOAK_PASSWORD=password
          - DB_VENDOR=mssql
          - DB_ADDR=sqlserver.wsstepbystep.perit.hu
          - DB_DATABASE=keycloak
          - DB_SCHEMA=keycloak
          - DB_USER=sa
          - DB_PASSWORD=Passw0rd
        command: ["-Djboss.socket.binding.port-offset=100"]  
        ports:
          - "8180:8180"
          - "8543:8543"
        networks: 
            back-tier-net:
                aliases:
                    - keycloak.wsstepbystep.perit.hu
        hostname: keycloak.wsstepbystep.perit.hu


    #####################################################################################                 
    webservice:
    #####################################################################################                 
        container_name: webservice
        image: webservice
        environment:
              - JAVA_OPTS=
              - WEBSERVICE_OPTS=-Dspring.profiles.active=dev-docker,dev-docker-sqlserver -Dserver.fqdn=webservice.wsstepbystep.perit.hu -Dserver.port=8400 
        ports:
            - "8400:8400"
        networks: 
            back-tier-net:
                aliases:
                    - webservice.wsstepbystep.perit.hu
            monitoring:
                aliases:
                    - webservice.wsstepbystep.perit.hu
        hostname: 'webservice.wsstepbystep.perit.hu'


    #####################################################################################                 
    webservice2:
    #####################################################################################                 
        container_name: webservice2
        image: webservice
        environment:
              - JAVA_OPTS=
              - WEBSERVICE_OPTS=-Dspring.profiles.active=dev-docker,dev-docker-sqlserver -Dserver.fqdn=webservice2.wsstepbystep.perit.hu -Dserver.port=8401 
        ports:
            - "8401:8401"
        networks: 
            back-tier-net:
                aliases:
                    - webservice2.wsstepbystep.perit.hu
            monitoring:
                aliases:
                    - webservice2.wsstepbystep.perit.hu
        hostname: 'webservice2.wsstepbystep.perit.hu'


    #####################################################################################                 
    prometheus:
    #####################################################################################                 
        container_name: prometheus
        image: wsstepbystep-prometheus
        volumes:
            - wsstepbystep_prometheus:/prometheus
        command: 
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=200h'
            - '--web.enable-lifecycle'
        ports:
            - '9090:9090'
        networks: 
            monitoring:
                aliases:
                    - prometheus.wsstepbystep.perit.hu
        labels:
            hu.perit.template.cluster: "monitoring"
        hostname: prometheus.wsstepbystep.perit.hu


    #####################################################################################                 
    nodeexporter:
    #####################################################################################                 
        image: prom/node-exporter:v0.18.1
        container_name: nodeexporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        restart: unless-stopped
        ports:
            - '9100:9100'
        networks: 
            monitoring:
                aliases:
                    - nodeexporter.wsstepbystep.perit.hu
        hostname: nodeexporter.wsstepbystep.perit.hu
        labels:
            hu.perit.template.cluster: "monitoring"


    #####################################################################################                 
    cadvisor:
    #####################################################################################                 
        image: gcr.io/google-containers/cadvisor:v0.36.0
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
        restart: unless-stopped
        ports:
            - '8080:8080'
        networks: 
            monitoring:
                aliases:
                    - cadvisor.wsstepbystep.perit.hu
        hostname: cadvisor.wsstepbystep.perit.hu
        labels:
            hu.perit.template.cluster: "monitoring"


    #####################################################################################                 
    grafana:
    #####################################################################################                 
        container_name: grafana
        image: wsstepbystep-grafana
        volumes:
            - wsstepbystep_grafana:/var/lib/grafana
        ports:
            - '3000:3000'
        networks: 
            monitoring:
                aliases:
                    - grafana.wsstepbystep.perit.hu
        hostname: grafana.wsstepbystep.perit.hu
        depends_on:
            - prometheus
        labels:
            hu.perit.template.cluster: "monitoring"

  
volumes:
    wsstepbystep_sqlserver:
    wsstepbystep_prometheus:
    wsstepbystep_grafana:
